### ISSUE TITLE
Cache location

### ISSUE THREAD

**Issue by blaircodesbadly** [rsJuuuuu/Divergent667#8]
Hey, I downloaded this base and a 667 cache from openRS2 archive but I get an OPCODE error "MISSING OPCODE 254 FOR ITEM 6" - do you still have the original cache for this?

**Comment by rsJuuuuu** [comment]
Hi,
yes, the cache is available from the post [here](https://www.rune-server.ee/runescape-development/rs-503-client-server/downloads/668648-667-cache-server-client-github.html).
